input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =

  follow_mouse = 1

  touchpad {
    scroll_factor=0.2
    natural_scroll = true
  }

  sensitivity = 0
}

misc {
  vfr = true
  vrr = 0
  disable_hyprland_logo = true
  force_default_wallpaper = 0
}

cursor {
  no_hardware_cursors = true
}

